name: setup-pesde
description: Installs the Pesde CLI along with Lune 

inputs:
  version:
    description: "Version of Pesde to install"
    required: false
  cache:
    description: "Whether or not to cache the Pesde install"
    default: false
    required: false
  token:
    description: "Token for publishing to the Pesde registry"
    required: false
  path:
    description: "The path to the pesde config file, typically used in monorepos"
    default: "."
    required: false

runs:
  using: composite
  steps:
    - name: Restore/Cache Pesde
      id: cache-pesde
      if: ${{ (inputs.cache == true || inputs.cache == 'true') }} 
      uses: actions/cache@v4
      with:
        path: |
          ~/.pesde
        key: ${{ runner.os }}-Pesde-${{ hashFiles(format('{0}/{1}', inputs.path, 'pesde.toml')) }}

    - name: Download release
      if: inputs.version != 'build' && steps.cache-pesde.outputs.cache-hit != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        case ${{ runner.arch }} in
          "X86" | "X64") fileArch="x86_64" ;;
          "ARM" | "ARM64") fileArch="aarch64" ;;
        esac

        case ${{ runner.os }} in
          Linux) pattern="*-linux-$fileArch.zip" ;;
          macOS) pattern="*-macos-$fileArch.zip" ;;
          Windows) pattern="*-windows-$fileArch.zip" ;;
        esac

        if ! [ -z ${{ inputs.version }} ]; then
          if [ ${ ${{inputs.version}}:0:1 } == 'v' ]; then
            version = ${{ inputs.version }}
          else
            version = 'v${{ inputs.version }}'
          fi
        fi

        gh release download "$version" -R pesde-pkg/pesde -p "$pattern"

    - name: Build Pesde
      if: inputs.version == 'build' && steps.cache-pesde.outputs.cache-hit != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        case ${{ runner.arch }} in
          "X86" | "X64") arch="x86_64" ;;
          "ARM" | "ARM64") arch="aarch64" ;;
        esac

        case ${{ runner.os }} in
          Linux) target="$arch-unknown-linux-gnu" ;;
          macOS) target="$arch-apple-darwin" ;;
          Windows) target="$arch-pc-windows-msvc" ;;
        esac

        git clone https://github.com/pesde-pkg/pesde
        mv pesde pesde_repo

        if [${{ runner.os }} == 'Linux']; then
          sudo apt-get update
          sudo apt-get install libdbus-1-dev pkg-config
        fi

        cargo build --bins --all-features --release --target "$target" --locked --manifest-path pesde_repo/Cargo.toml
        
        if [${{ runner.os }} == 'Windows' ]; then
          mv pesde_repo/target/"$target"/release/pesde.exe pesde.exe
        else
          mv pesde_repo/target/"$target"/release/pesde pesde
        fi

        chmod +x pesde
        
    - name: Install releases
      if: inputs.version != 'build' && steps.cache-pesde.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mv pesde*.zip pesde.zip
        unzip pesde.zip
        chmod +x pesde
        
    - run: ./pesde self-install
      if: steps.cache-pesde.outputs.cache-hit != 'true'
      shell: bash

    - name: Add bins to PATH
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        echo "$HOME/.pesde/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Add bins to PATH
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo -e "$HOME/.pesde/bin" >> $GITHUB_PATH

    - name: Remove artifacts
      if: steps.cache-pesde.outputs.cache-hit != 'true'
      shell: bash
      run: |
        if [${{ runner.os }} == 'Windows']; then
          rm pesde.exe
        else
          rm pesde
        fi
        if [${{ inputs.version }} == 'build']; then
          rm -r pesde_repo
        else
          rm pesde.zip
        fi

    - name: Authenticate with Pesde
      if: inputs.token != ''
      shell: bash
      run: pesde auth login --token "${{ inputs.token }}"

branding:
  icon: box
  color: blue
