name: Action Test
on: 
  workflow_dispatch:
  push:
    paths:
      - '**.yml'
      - 'pesde.toml'
      - 'test/**'
  pull_request:
    paths:
      - '**.yml'
    tags-ignore:
      - v*
  workflow_call:
    outputs:
      passed:
        value: ${{ jobs.test-cache.outputs.passed && jobs.test-build.passed && jobs.test-version.outputs.passed }}

defaults:
  run:
    shell: bash

jobs:
  test-cache:
    uses: ./.github/workflows/env.yml
    with:
      cache: true

  test-build:
    uses: ./.github/workflows/env.yml
    with:
      version: build

  test-version:
    uses: ./.github/workflows/env.yml
    with:
      version: 0.7.0-rc.6
